-- MySQL Script generated by MySQL Workbench
-- Tue Apr 22 14:33:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetointegrador1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetointegrador1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetointegrador1` DEFAULT CHARACTER SET utf8mb3 ;
USE `projetointegrador1` ;

-- -----------------------------------------------------
-- Table `projetointegrador1`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador1`.`setor` (
  `idsetor` INT NOT NULL AUTO_INCREMENT,
  `nomesetor` VARCHAR(100) NOT NULL,
  `tipo` ENUM('Individual', 'Coletivo') NOT NULL,
  PRIMARY KEY (`idsetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador1`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador1`.`animais` (
  `idanimais` INT NOT NULL AUTO_INCREMENT,
  `nomeanimal` VARCHAR(100) NOT NULL,
  `sexo` ENUM('Masculino', 'Feminino') NOT NULL,
  `nascimento` VARCHAR(10) NOT NULL,
  `raca` VARCHAR(100) NULL DEFAULT NULL,
  `foto_frente` VARCHAR(255) NULL DEFAULT NULL,
  `foto_lado` VARCHAR(255) NULL DEFAULT NULL,
  `foto_tam` VARCHAR(255) NULL DEFAULT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idsetor` INT NOT NULL,                                 --coluna configurada como chave estrangeira da tabela 'setor' para vincular setor e animal
  `castracao` ENUM('Sim', 'Não') NOT NULL,
  `porte` ENUM('Pequeno', 'Pequeno/Médio', 'Médio/Grande', 'Médio', 'Grande') NOT NULL,
  `aptidao` TEXT NOT NULL,
  `vacina` DATE NULL DEFAULT NULL,
  `vermifugo` DATE NULL DEFAULT NULL,
  `bg_color` VARCHAR(20) NULL DEFAULT NULL,
  `data_criacao` DATE NULL DEFAULT NULL,
  `data_atualizacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idanimais`),
  INDEX `idsetor_idx` (`idsetor` ASC) VISIBLE,
  CONSTRAINT `idsetor`
    FOREIGN KEY (`idsetor`)
    REFERENCES `projetointegrador1`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projetointegrador1`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador1`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeusuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `last_login` DATE NULL DEFAULT NULL,                                --vincular a data de ultimo login do usuario com essa coluna
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
