# Generated by Django 5.2 on 2025-09-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorMod',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('type', models.CharField(choices=[('I', 'Individual'), ('C', 'Coletivo')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PetsMod',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=10)),
                ('birth', models.DateField(blank=True, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, choices=[('P', 'Pequeno'), ('PM', 'Peq/Médio'), ('M', 'Médio'), ('MG', 'Med/Grande'), ('G', 'Grande')], default='P', max_length=20)),
                ('vaccine', models.DateField(blank=True, null=True)),
                ('vermifuge', models.DateField(blank=True, null=True)),
                ('aptitude', models.CharField(choices=[('AP', 'Apto'), ('IN', 'Inapto'), ('PR', 'Em preparo'), ('AD', 'Adotado')], default='AP', max_length=2)),
                ('front_photo', models.ImageField(upload_to='pets/photos/front/%Y/%m/')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='pets/photos/side/%Y/%m/')),
                ('size_photo', models.ImageField(blank=True, null=True, upload_to='pets/photos/size/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bg_color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.sectormod')),
            ],
        ),
    ]
