# Generated by Django 5.2 on 2025-10-10 19:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEventMod',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=255)),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('change_status', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_events', to='pets.petsmod')),
            ],
        ),
    ]
